# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1247f5b5306f356f7a647414c8c5f30878e8849dbcbbb6b5b78ebb7c8b7e40a224baddf53f747449c820607b427f64dcab53515b19156cc705c23cdc2ee034b1

test:
  secret_key_base: 9f96ed010b55c77a91768c2f19cbd05e5c97c4c35c3cf927a84e0a1ee2db723e079b2cd1d42598fdea7f8ec369c12ea24e803e428d6566da26debdd6469737d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
